/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sf_rhash_Bindings */

#ifndef _Included_org_sf_rhash_Bindings
#define _Included_org_sf_rhash_Bindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sf_rhash_Bindings
 * Method:    rhash_library_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sf_rhash_Bindings_rhash_1library_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    rhash_count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sf_rhash_Bindings_rhash_1count
  (JNIEnv *, jclass);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    rhash_msg
 * Signature: (I[BII)J
 */
JNIEXPORT jlong JNICALL Java_org_sf_rhash_Bindings_rhash_1msg
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    rhash_file
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_sf_rhash_Bindings_rhash_1file
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    rhash_print_bytes
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_sf_rhash_Bindings_rhash_1print_1bytes
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    freeHashObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sf_rhash_Bindings_freeHashObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    cloneHashObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sf_rhash_Bindings_cloneHashObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    rhash_is_base32
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sf_rhash_Bindings_rhash_1is_1base32
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    compareHashObjects
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sf_rhash_Bindings_compareHashObjects
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sf_rhash_Bindings
 * Method:    hashcodeForHashObject
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_sf_rhash_Bindings_hashcodeForHashObject
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
